project:
  type: website
  render:
    - index.qmd
    - chapters/chapter1.qmd

website:
  page-navigation: true
  title: "Educational resource template for Python"
  site-url: "https://github.com/InseeFrLab/AIML4OS-template-quarto-python"
  repo-url: "https://github.com/InseeFrLab/AIML4OS-template-quarto-python"
  repo-actions: [edit, source, issue]
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Introduction
      - href: chapters/chapter1.qmd
        text: A complete example

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

filters:
  - export-metadata.lua

