name: Build the website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Install uv
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          python-version: 3.12

      # Step 2b: Restore uv environment
      - name: Restore environment
        run: uv sync

      # Step 2c: Install Python dependencies
      - name: Install Python dependencies
        run: uv run pip install -r requirements.txt

      # Step 2d: Install ipykernel to make uv environment visible to Quarto
      - name: Install ipykernel
        run: uv run pip install ipykernel

      # Step 2e: Debug – list installed packages
      - name: List installed Python packages
        run: uv run pip list

      # Step 3: Set up Quarto
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # Step 4: Render Quarto (HTML) using uv environment
      - name: Render HTML
        run: uv run quarto render --execute --no-cache

      # Step 4b: Render Quarto to ipynb using uv environment
      - name: Render ipynb
        run: uv run quarto render --to ipynb --execute --no-cache

      # Step 5: Publish to GitHub Pages
      - name: Publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
